---
# tasks file for build_app
- name: Creates directory
  file:
    path: "{{ path_to_dockerfile }}"
    state: directory

- name: Copy the Dockerfile from localhost  to builder host
  copy:
    src: Dockerfile
    dest: "{{ path_to_dockerfile }}"
  

- name: build_image
  docker_image:
    name: "gcr.io/{{ project_ID }}/{{ docker_image_name }}"
    tag: "{{ version_release_app }}"
    path: "{{ path_to_dockerfile }}"
    pull: no
    state: present
  
- name: Docker Login
  shell: (echo "{{ service_account_key }}" | base64 -d) | docker login -u _json_key --password-stdin https://gcr.io/{{ project_ID }}
      
- name: Push image to GCP container registry
  docker_image:
    name: "gcr.io/{{ project_ID }}/{{ docker_image_name }}"
    tag: "{{ version_release_app }}"
    push: yes